version: "3.9"

services:
  # MQTT Broker
  broker:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/config/passwd
      - mosq_data:/mosquitto/data
      - mosq_log:/mosquitto/log

  # MQTT Simulator (sensor data generator)
  mqtt-sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-sim-live
    restart: unless-stopped
    environment:
      BROKER: broker
      PORT: 1883
      PREFIX: building/demo
      QOS: 0
      INTERVAL: 5  # Send data every 5 seconds for live demo
    depends_on:
      - broker
    command: python mqtt_simulator.py

  # Live Real-time Dashboard
  live-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-dashboard
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MQTT_BROKER: broker
      MQTT_PORT: 1883
    depends_on:
      - broker
    command: python realtime_dashboard.py

  # Live Sensor API
  live-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      MQTT_BROKER: broker
      MQTT_PORT: 1883
    depends_on:
      - broker
    command: python live_sensor_api.py

  # Test script (optional)
  test-live:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-live
    depends_on:
      - live-dashboard
      - live-api
      - mqtt-sim
    command: sleep 10 && python test_live_system.py
    profiles:
      - test

volumes:
  mosq_data:
  mosq_log:
