services:
  - type: web
    name: mqtt-simulator
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: BROKER
        value: broker.hivemq.com  # MQTT broker رایگان
      - key: PORT
        value: 8883  # MQTT over SSL
      - key: PREFIX
        value: building/demo
      - key: QOS
        value: 0
      - key: INTERVAL
        value: 10
      - key: MQTT_USER
        value: ""  # بدون احراز هویت برای broker رایگان
      - key: MQTT_PASS
        value: ""
      - key: PORT
        value: 10000  # پورت داخلی Render
    healthCheckPath: /health
