services:
  - type: web
    name: sensor-api
    env: python
    pythonVersion: 3.11.0
    buildCommand: pip install --upgrade pip && pip install -r render_requirements.txt
    startCommand: gunicorn render_api:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
