services:
  - type: web
    name: sensor-api-v2
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health
