services:
  - type: web
    name: sensor-api
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
