services:
  - type: web
    name: digitaltwin-sensor-dashboard
    env: python
    plan: free
    buildCommand: pip install -r render_requirements.txt
    startCommand: python render_dashboard.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000